package org.nxtspec.app

import org.nxtspec.DatabaseConfig
import org.nxtspec.repository.DatabaseType
import javax.sql.DataSource

/**
 * Stops the start when the inbox table has no headers column.
 *
 * The bundled migration V10 adds the column to the default schema. A custom inbox table does not
 * get the migration, and every inbox insert would then fail one message at a time.
 */
fun requireInboxHeadersColumn(dataSource: DataSource, database: DatabaseConfig, type: DatabaseType) {
    val table = database.inboxTableName
    val column = database.columnMapping.inbox.headers
    if (hasColumn(dataSource, table, column)) return

    val alter = when (type) {
        DatabaseType.POSTGRESQL -> "ALTER TABLE \"$table\" ADD COLUMN \"$column\" JSONB NOT NULL DEFAULT '{}';"
        DatabaseType.SQLSERVER -> "ALTER TABLE [$table] ADD [$column] NVARCHAR(MAX) NOT NULL DEFAULT '{}';"
    }
    throw StartupFailedException(
        "The inbox table '$table' has no column '$column'. QueueBox stores the message headers " +
            "there. Add the column, then start QueueBox again: $alter"
    )
}

/**
 * Stops the start when the outbox table has no sequence column.
 *
 * The bundled migration V11 adds the column to the default schema. A custom outbox table does not
 * get the migration, and the claim cannot order the rows of one key without it.
 */
fun requireOutboxSequenceColumn(dataSource: DataSource, database: DatabaseConfig, type: DatabaseType) {
    val table = database.outboxTableName
    val column = database.columnMapping.outbox.sequence
    if (hasColumn(dataSource, table, column)) return

    val key = database.columnMapping.outbox.key
    val state = database.columnMapping.outbox.state
    val alter = when (type) {
        DatabaseType.POSTGRESQL ->
            "ALTER TABLE \"$table\" ADD COLUMN \"$column\" BIGINT GENERATED BY DEFAULT AS IDENTITY; " +
                "CREATE INDEX ON \"$table\" (\"$key\", \"$column\") WHERE \"$state\" IN ('pending', 'processing');"
        DatabaseType.SQLSERVER ->
            "ALTER TABLE [$table] ADD [$column] BIGINT IDENTITY(1,1) NOT NULL; " +
                "CREATE INDEX ix_${table}_key_sequence ON [$table] ([$key], [$column]);"
    }
    throw StartupFailedException(
        "The outbox table '$table' has no column '$column'. QueueBox orders the rows of one key " +
            "by it. Add the column, then start QueueBox again: $alter"
    )
}

private fun hasColumn(dataSource: DataSource, table: String, column: String): Boolean =
    dataSource.connection.use { conn ->
        // Postgres folds an unquoted name to lower case, and the metadata lookup matches exactly.
        setOf(table, table.lowercase(), table.uppercase()).any { name ->
            conn.metaData.getColumns(null, null, name, null).use { rows ->
                generateSequence { if (rows.next()) rows.getString("COLUMN_NAME") else null }
                    .any { it.equals(column, ignoreCase = true) }
            }
        }
    }
